name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: ls -l ./dist